branches:
  only:
    - master

language: node_js
node_js:
  - "10"
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "modupdates.com"
  skip_cleanup: true
  cache_control: "max-age=21600"
  local_dir: dist