branches:
  only:
    - master

language: node_js
node_js:
  - "10"
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "modupdates.com"
  skip_cleanup: true
  cache_control: "max-age=21600"
  local_dir: dist
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS -s $AWS_SECRET -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,stage'