branches:
  only:
    - master

language: node_js
node_js:
  - "10"
install:
  - npm i cloudfront-invalidate
script:
  - npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "modupdates.com"
  skip_cleanup: true
  cache_control: "max-age=21600"
  local_dir: dist
after_deploy:
  - cloudfront-invalidate -d $CLOUDFRONT_DISTRIBUTION_ID