branches:
  only:
    - master

language: node_js
node_js:
  - "10"

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "modupdates.com"
  skip_cleanup: true
  local_dir: dist

script:
  - npm run build